#!/bin/bash
echo "enter number of students:"
read n
a=1
for((a=1;a<=n;a++))
do
echo "enter student name:"
read student
echo "english marks"
read english
echo "science marks"
read science
sum=$(($english+$science))
per=$((100*sum/200))
echo "total=" $sum
echo "percentage=" $per
done
